steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-m', '30g', '-t', 'gcr.io/semiotic-vial-255604/diseaseprediction:alpha', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/semiotic-vial-255604/diseaseprediction:alpha']
options:
  machineType: 'N1_HIGHCPU_32'
timeout: 9600s
